# @package _global_

online_eval:
  _target_: omnigibson.learning.eval.Evaluator
  cfg:
    write_video: true
    headless: ${headless}
    env_type: sim
    task: ${task}
    robot: ${robot}
    use_task_info: ${data.use_task_info}
    policy_name: ${arch_name}
    max_steps: 1000
    model:
      _target_: omnigibson.learning.policies.LocalPolicy
