# @package _global_

online_eval:
  _target_: omnigibson.learning.eval.Evaluator
  cfg:
    write_video: true
    partial_scene_load: false
    eval_on_train_instances: false
    headless: ${headless}
    env_wrapper:
      # _target_: omnigibson.learning.wrappers.wbvima_wrapper.WBVIMAWrapper
      _target_: omnigibson.learning.wrappers.rgb_low_res_wrapper.RGBLowResWrapper
    task: ${task}
    robot: ${robot}
    policy_name: ${arch_name}
    max_steps: 1000
    model:
      _target_: omnigibson.learning.policies.LocalPolicy
