# @package _global_

policy_name: bcrnn

# ====== BCRNN specific ======
horizon: 5
num_latest_obs: 5

# ------ module ------
module:
  _target_: il_lib.policies.BC_RNN
  prop_dim: 21
  prop_keys: ["odom/base_velocity", "qpos/torso", "qpos/left_arm", "qpos/left_gripper", "qpos/right_arm", "qpos/right_gripper"]
  # ====== Feature Extractors ======
  feature_extractors:
    - proprioception:
      _target_: il_lib.nn.mlp.MLP
      input_dim: ${prop_dim}
      hidden_dim: 512
      output_dim: 512
      hidden_depth: 2
      add_output_activation: true
    - rgb:
      _target_: il_lib.nn.resnet.MultiviewResNet18
      views: 
      - robot_r1::robot_r1:left_realsense_link:Camera:0::rgb
      - robot_r1::robot_r1:right_realsense_link:Camera:0::rgb
      - robot_r1::robot_r1:zed_link:Camera:0::rgb
      resnet_output_dim: 512
      resnet_token_dim: 512
      resnet_load_pretrained: true
      resnet_pretrained_ckpt_path: ${resnet_pretrained_ckpt_path}
      resnet_enable_random_crop: true
      resnet_random_crop_size: 94
  # ====== Feature Fusion ======
  feature_fusion_hidden_depth: 2
  feature_fusion_hidden_dim: 512
  feature_fusion_output_dim: 512
  feature_fusion_activation: "relu"
  feature_fusion_add_input_activation: false
  feature_fusion_add_output_activation: true
  rnn_n_layers: 2
  rnn_hidden_dim: 512
  # ====== Action ======
  action_dim: 21
  action_net_gmm_n_modes: 5
  action_net_hidden_dim: 128
  action_net_hidden_depth: 3
  action_net_activation: relu
  deterministic_inference: true
  gmm_low_noise_eval: true
  optimizer: "adam"

data_module:
  obs_window_size: ${num_latest_obs}
  ctx_len: ${horizon}
  use_action_chunks: false
  visual_obs_types: ["rgb"]
  load_task_info: false
  multi_view_cameras:
    - robot_r1::robot_r1:left_realsense_link:Camera:0
    - robot_r1::robot_r1:right_realsense_link:Camera:0
    - robot_r1::robot_r1:zed_link:Camera:0

robot:
  type: R1Pro
  controllers: